;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Attribute.Charisma",DevComment="")
+GameplayTagList=(Tag="Attribute.HitPoints",DevComment="")
+GameplayTagList=(Tag="Attribute.HitPointsMax",DevComment="")
+GameplayTagList=(Tag="Attribute.MainJobLevel",DevComment="")
+GameplayTagList=(Tag="Attribute.ManaPoints",DevComment="")
+GameplayTagList=(Tag="Attribute.ManaPointsMax",DevComment="")
+GameplayTagList=(Tag="Attribute.SubJobLevel",DevComment="")
+GameplayTagList=(Tag="Attribute.TacticalPoints",DevComment="")
+GameplayTagList=(Tag="Attribute.TacticalPointsMax",DevComment="")
+GameplayTagList=(Tag="EquipSlot.Body",DevComment="")
+GameplayTagList=(Tag="Input.Hotbar.1",DevComment="")
+GameplayTagList=(Tag="Input.Hotbar.2",DevComment="")
+GameplayTagList=(Tag="Input.Hotbar.3",DevComment="")
+GameplayTagList=(Tag="Input.Hotbar.4",DevComment="")
+GameplayTagList=(Tag="Input.Hotbar.5",DevComment="")
+GameplayTagList=(Tag="Input.Hotbar.6",DevComment="")
+GameplayTagList=(Tag="Input.Hotbar.7",DevComment="")
+GameplayTagList=(Tag="Input.Hotbar.8",DevComment="")
+GameplayTagList=(Tag="Input.Hotbar.Left.DPad.Down",DevComment="")
+GameplayTagList=(Tag="Input.Hotbar.Left.DPad.Left",DevComment="")
+GameplayTagList=(Tag="Input.Hotbar.Left.DPad.Right",DevComment="")
+GameplayTagList=(Tag="Input.Hotbar.Left.DPad.Up",DevComment="")
+GameplayTagList=(Tag="Input.Hotbar.Left.Face.Bottom",DevComment="")
+GameplayTagList=(Tag="Input.Hotbar.Left.Face.Left",DevComment="")
+GameplayTagList=(Tag="Input.Hotbar.Left.Face.Right",DevComment="")
+GameplayTagList=(Tag="Input.Hotbar.Left.Face.Top",DevComment="")
+GameplayTagList=(Tag="Input.Hotbar.Right.DPad.Down",DevComment="")
+GameplayTagList=(Tag="Input.Hotbar.Right.DPad.Left",DevComment="")
+GameplayTagList=(Tag="Input.Hotbar.Right.DPad.Right",DevComment="")
+GameplayTagList=(Tag="Input.Hotbar.Right.DPad.Up",DevComment="")
+GameplayTagList=(Tag="Input.Hotbar.Right.Face.Bottom",DevComment="")
+GameplayTagList=(Tag="Input.Hotbar.Right.Face.Left",DevComment="")
+GameplayTagList=(Tag="Input.Hotbar.Right.Face.Right",DevComment="")
+GameplayTagList=(Tag="Input.Hotbar.Right.Face.Top",DevComment="")
+GameplayTagList=(Tag="Job.Race",DevComment="")

