;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Attribute.Attack.Magic",DevComment="")
+GameplayTagList=(Tag="Attribute.Attack.Physical",DevComment="")
+GameplayTagList=(Tag="Attribute.Charisma",DevComment="")
+GameplayTagList=(Tag="Attribute.Defense.Magic",DevComment="")
+GameplayTagList=(Tag="Attribute.Defense.Physical",DevComment="")
+GameplayTagList=(Tag="Attribute.HitPoints",DevComment="")
+GameplayTagList=(Tag="Attribute.HitPointsMax",DevComment="")
+GameplayTagList=(Tag="Attribute.MainJobLevel",DevComment="")
+GameplayTagList=(Tag="Attribute.ManaPoints",DevComment="")
+GameplayTagList=(Tag="Attribute.ManaPointsMax",DevComment="")
+GameplayTagList=(Tag="Attribute.Resistance.Elemental.Dark",DevComment="")
+GameplayTagList=(Tag="Attribute.Resistance.Elemental.Earth",DevComment="")
+GameplayTagList=(Tag="Attribute.Resistance.Elemental.Fire",DevComment="")
+GameplayTagList=(Tag="Attribute.Resistance.Elemental.Ice",DevComment="")
+GameplayTagList=(Tag="Attribute.Resistance.Elemental.Light",DevComment="")
+GameplayTagList=(Tag="Attribute.Resistance.Elemental.Lightning",DevComment="")
+GameplayTagList=(Tag="Attribute.Resistance.Elemental.Water",DevComment="")
+GameplayTagList=(Tag="Attribute.Resistance.Elemental.Wind",DevComment="")
+GameplayTagList=(Tag="Attribute.Skill.Defensive.Evasion",DevComment="")
+GameplayTagList=(Tag="Attribute.Skill.Defensive.Guard",DevComment="")
+GameplayTagList=(Tag="Attribute.Skill.Defensive.Parry",DevComment="")
+GameplayTagList=(Tag="Attribute.Skill.Defensive.Shield",DevComment="")
+GameplayTagList=(Tag="Attribute.Skill.Magic.Divine",DevComment="")
+GameplayTagList=(Tag="Attribute.Skill.Magic.Elemental",DevComment="")
+GameplayTagList=(Tag="Attribute.Skill.Magic.Healing",DevComment="")
+GameplayTagList=(Tag="Attribute.Skill.Weapon.Club",DevComment="")
+GameplayTagList=(Tag="Attribute.Skill.Weapon.GreatSword",DevComment="")
+GameplayTagList=(Tag="Attribute.Skill.Weapon.Sword",DevComment="")
+GameplayTagList=(Tag="Attribute.SubJobLevel",DevComment="")
+GameplayTagList=(Tag="Attribute.TacticalPoints",DevComment="")
+GameplayTagList=(Tag="Attribute.TacticalPointsMax",DevComment="")
+GameplayTagList=(Tag="DamageType.Elemental.Dark",DevComment="")
+GameplayTagList=(Tag="DamageType.Elemental.Earth",DevComment="")
+GameplayTagList=(Tag="DamageType.Elemental.Fire",DevComment="")
+GameplayTagList=(Tag="DamageType.Elemental.Ice",DevComment="")
+GameplayTagList=(Tag="DamageType.Elemental.Light",DevComment="")
+GameplayTagList=(Tag="DamageType.Elemental.Lightning",DevComment="")
+GameplayTagList=(Tag="DamageType.Elemental.Water",DevComment="")
+GameplayTagList=(Tag="DamageType.Elemental.Wind",DevComment="")
+GameplayTagList=(Tag="EquipSlot.Back",DevComment="")
+GameplayTagList=(Tag="EquipSlot.Body",DevComment="")
+GameplayTagList=(Tag="EquipSlot.Ear.1",DevComment="")
+GameplayTagList=(Tag="EquipSlot.Ear.2",DevComment="")
+GameplayTagList=(Tag="EquipSlot.Feet",DevComment="")
+GameplayTagList=(Tag="EquipSlot.Hands",DevComment="")
+GameplayTagList=(Tag="EquipSlot.Head",DevComment="")
+GameplayTagList=(Tag="EquipSlot.Legs",DevComment="")
+GameplayTagList=(Tag="EquipSlot.Neck",DevComment="")
+GameplayTagList=(Tag="EquipSlot.Ring.1",DevComment="")
+GameplayTagList=(Tag="EquipSlot.Ring.2",DevComment="")
+GameplayTagList=(Tag="EquipSlot.Special",DevComment="")
+GameplayTagList=(Tag="EquipSlot.Waist",DevComment="")
+GameplayTagList=(Tag="Input.Hotbar.1",DevComment="")
+GameplayTagList=(Tag="Input.Hotbar.2",DevComment="")
+GameplayTagList=(Tag="Input.Hotbar.3",DevComment="")
+GameplayTagList=(Tag="Input.Hotbar.4",DevComment="")
+GameplayTagList=(Tag="Input.Hotbar.5",DevComment="")
+GameplayTagList=(Tag="Input.Hotbar.6",DevComment="")
+GameplayTagList=(Tag="Input.Hotbar.7",DevComment="")
+GameplayTagList=(Tag="Input.Hotbar.8",DevComment="")
+GameplayTagList=(Tag="Input.Hotbar.Left.DPad.Down",DevComment="")
+GameplayTagList=(Tag="Input.Hotbar.Left.DPad.Left",DevComment="")
+GameplayTagList=(Tag="Input.Hotbar.Left.DPad.Right",DevComment="")
+GameplayTagList=(Tag="Input.Hotbar.Left.DPad.Up",DevComment="")
+GameplayTagList=(Tag="Input.Hotbar.Left.Face.Bottom",DevComment="")
+GameplayTagList=(Tag="Input.Hotbar.Left.Face.Left",DevComment="")
+GameplayTagList=(Tag="Input.Hotbar.Left.Face.Right",DevComment="")
+GameplayTagList=(Tag="Input.Hotbar.Left.Face.Top",DevComment="")
+GameplayTagList=(Tag="Input.Hotbar.Right.DPad.Down",DevComment="")
+GameplayTagList=(Tag="Input.Hotbar.Right.DPad.Left",DevComment="")
+GameplayTagList=(Tag="Input.Hotbar.Right.DPad.Right",DevComment="")
+GameplayTagList=(Tag="Input.Hotbar.Right.DPad.Up",DevComment="")
+GameplayTagList=(Tag="Input.Hotbar.Right.Face.Bottom",DevComment="")
+GameplayTagList=(Tag="Input.Hotbar.Right.Face.Left",DevComment="")
+GameplayTagList=(Tag="Input.Hotbar.Right.Face.Right",DevComment="")
+GameplayTagList=(Tag="Input.Hotbar.Right.Face.Top",DevComment="")
+GameplayTagList=(Tag="ItemContainer.KeyItems",DevComment="")
+GameplayTagList=(Tag="Job.BlackMage",DevComment="")
+GameplayTagList=(Tag="Job.Monk",DevComment="")
+GameplayTagList=(Tag="Job.Race",DevComment="")
+GameplayTagList=(Tag="Job.Race.Hume",DevComment="")
+GameplayTagList=(Tag="Job.RedMage",DevComment="")
+GameplayTagList=(Tag="Job.Thief",DevComment="")
+GameplayTagList=(Tag="Job.Warrior",DevComment="")
+GameplayTagList=(Tag="Job.WhiteMage",DevComment="")

